### PR TITLE
Fix: import aliases on production builds

### LINKED ISSUE #77: Vite import aliases don't work when building for production
**Describe the bug**
Vite import aliases for SCSS files don't work when building for production.

**To Reproduce**
Ive added `<link rel="stylesheet" href="/@includes/styles/styles.scss" />` to my `base.njk` and this works beautifully in HMR mode. But when I try to build for production (`npx slinkity`) i get the following error:

```
[vite:load-fallback] Could not load /Users/bram/Developer/supple-kit/eleventy-supple-starter/.11ty-build-U0dn1s/_includes/styles/styles.scss (imported by .11ty-build-U0dn1s/index.html): ENOENT: no such file or directory, open '/Users/bram/Developer/supple-kit/eleventy-supple-starter/.11ty-build-U0dn1s/_includes/styles/styles.scss'
[11ty] Unhandled rejection in promise: (more in DEBUG output)
```

**Expected behavior**
I expect the build to succeed with a compiled CSS file. 

**(please complete the following information):**
 - OS: MacOS 12.0.1
 - Browser: n/a
 - Version: `0.3.3`
 - NodeJS: `14.18.1`

### PR DESCRIPTION
**Pull request by Holben888**
Resolves #77 

- use user's input directory instead of our temporary build directory when resolving aliases
- move _all_ React prebundling logic inside that try / catch. Noticed another issue when attempting a React-less production build!

### CODE REVIEW

File: src/cli/vite.js [hunk 1]
```diff
@@ -29,55 +29,68 @@ function getResolvedAliases(dir) {
...
-      build: {
-        outDir: dir.output,
-        emptyOutDir: true,
-        rollupOptions: {
-          input: inputFiles,
-          output: {
-            manualChunks: {
-              react: ['react'],
+    await vite.build(
+      vite.mergeConfig(
```
Comment (Holben888) [inline src/cli/vite.js:80]: Learned about Vite's `mergeConfig` helper recently. Want to refactor all `...` spreads across our configs when we find them!
